baseurl: "/"
languageCode: en-us
title: A Hugo website
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Présentation
      url: /homepage/
      weight: 1
    # - name: CV
    #   url: /cv/CV Tiran-Cappello Alix - Data scientist.pdf
    #   weight: 2
    - name: Shiny
      url: /shiny/
      weight: 5
    - name: Articles et Publications
      url: /post/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
    
    - name: Exemple d'application
      url: https://shiny.atc-data.fr/app-behavioral-data-analysis/
      
  #  - name: GitHub
  #    url: https://github.com/rstudio/blogdown
      
  #  - name: Twitter
  #    url: https://twitter.com/rstudio
      
      
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
