---
title: "Présentation"
author: "ATC"
date: "24/03/2021"
slug: "homepage"
output: html_document
---

<!-- ## Services -->
<!-- Nous proposons des services personnalisés d'analyse de données de type variés. Nous développons des solutions adaptées et spécifiques à chaque demande. -->

<!--   - Visualisations de données complexes -->
<!--   - Extraction et mise en forme automatique -->
<!--   - Analyse dynamique sur applications Shiny -->
<!--   - Utilisation de modèles de machine learning et deep learning  -->
<!--   - Interface intuitive et facile d'accès  -->

<!-- Des exemples d'outils que nous proposons sont disponibles [ici](http://localhost:4321/shiny/) -->

<!-- ## A qui s'adressent nos services ? -->
<!-- Les solutions proposées ici s'adressent avant tout aux entreprises de taille variable, collectivitées ou agriculteurs qui peuvent avoir des besoins ponctuels en traitement et analyse de données.  -->

<!-- Des solutions à plus grande échelle peuvent également être proposées. -->

## Qui suis-je ?
Je m'appelle Alix Tiran-Cappello et je suis titulaire d'un doctorat en neurosciences de l'université d'Aix-Marseille et j'ai pu bénéficier d'un post-docorat d'un an aux Etats-Unis à l'université Northwestern à Chicago. Durant ces nombreuses années à travailler sur des sujets complexes en neurosciences, j'ai pu utiliser et maitriser plusieurs solutions d'analyses pour des problèmes variés : 

  - analyses de données comportementales
  - de l'activité neuronales via différentes modalités incluant l'utilisation de nouvelles méthodes statistiques.
  - traitement automatisés de plusieurs centaines de fichiers
  - analyse de vidéos

##  Un background diversifié
Grâce à mon parcours via l'Ecole Normale Supérieur de Lyon, j'ai pu bénéficier d'un enseignement riche en concepts mathématiques et d'une bonne formation sur certains outils de base en programmation comme R et Matlab.

Par ailleurs durant plusieurs année de thèses et de post-doc, j'ai pu progressivement développer des compétences pour l'analyse statistique:

  - tests uni- et multivariés
  - modèles linéaires, mixtes, et généralisés
  - familiarisation avec les outils de deep learning durant mon post-doc
  - Bonne connaissance des bonnes pratiques en machine learnning

## Approche technique
La plupart des outils que nous proposés sont basés sur le logiciel R. Il s'agit d'un logiciel d'analyse et de calcul statistique gratuit et en accès libre. De nombreux formats de données sont facilement importables et utilisables directement via de nombreuses extensions développées en accès libre.

R permet aussi de développer des interfaces interactives complètes en utilisant l'extension Shiny permettant à l'utilisateur de choisir le type d'analyses à conduire, différents modes de visualisation, et d'exporter les données traitées. [Des exemples de simples applications sont disponibles ici](https://site.atc-data.fr/shiny/)

Cet ensemble est mis à profit pour proposer des outils dans lequel l'intervention de l'utilisateur pour être adapté, allant de pré-traitements limités à un ensemble cohérent et complètement automatisé.