---
title: 'Example of machine learning'
author: alix
date: '2021-04-14'
slug: example-of-machine-learning
categories: []
tags: []
draft: true
---

```{r setup, include=FALSE}

```

```{r}
library(tidyverse)
library(tidymodels)
library(tvthemes)
theme_set(theme_avatar(title.font = "Slayer",
                        text.font = "Slayer",
                        title.size = 14))

theme_set(theme_classic())
```

```{r}
avatar_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/avatar.csv")
```

```{r}
avatar_raw %>% 
  count(character, sort = TRUE)
```

```{r}
library(tidytext)
 
avatar_raw %>% 
  filter(!is.na(character_words)) %>% 
  mutate(book = fct_inorder(book),
         character = fct_lump_n(character, 10)) %>% 
  count(book, character) %>% 
  mutate(character = reorder_within(character, n, book)) %>% 
  ggplot(aes(n, character, fill = book)) + geom_col() + 
  facet_wrap(~book, scales = "free") +
  scale_y_reordered()+
  scale_fill_manual(values = c(avatar_pal("WaterTribe")(1),
                                avatar_pal("EarthKingdom")(1),
                                avatar_pal("FireNation")(5)[2]
                                ))

```

```{r}
avatar <- avatar_raw %>% 
  filter(!is.na(character_words)) %>% 
  mutate(aang = ifelse(character == "Aang", "Aang", "Other")) %>% 
  select(aang, book, text = character_words)


avatar %>% 
  filter(aang == "Aang") %>% 
  sample_n(20) %>% 
  pull(text)
```

```{r}
library(tidylo)
avatar_lo <- avatar %>% 
  unnest_tokens(word, text) %>% 
  count(aang, word) %>% 
  bind_log_odds(aang, word, n) %>% 
  arrange(-log_odds_weighted)
```

```{r}
avatar_lo %>% 
  group_by(aang) %>% 
  slice_max(log_odds_weighted, n = 15) %>% 
  ungroup() %>% 
  mutate(word = reorder(word, log_odds_weighted)) %>% 
  ggplot(aes(log_odds_weighted, word, fill = aang)) + 
  geom_col()+
  facet_wrap(~aang, scales = "free") +
  scale_fill_avatar("AirNomads")
  
```

# Text engineering

```{r}
library(textfeatures)
tf <- textfeatures(avatar, sentiment = FALSE, word_dims = 0, normalize = FALSE)

tf %>% 
  bind_cols(avatar) %>% 
  group_by(aang) %>% 
  summarise(across(starts_with("n_"), mean)) %>% 
  pivot_longer(starts_with("n_"), names_to = "text_features") %>% 
  filter(value > 0.01) %>% 
  mutate(text_features = fct_reorder(text_features, -value)) %>% 
  ggplot(aes(aang, value, fill = aang)) +
  geom_col(position = "dodge") +
  facet_wrap(~text_features, scales = "free", ncol = 6) +
  scale_fill_avatar("AirNomads")
```

```{r}
library(tidymodels)

set.seed(123)
avatar_split <- initial_split(avatar, strata = aang)
avatar_train <- training(avatar_split)
avatar_test <- testing(avatar_split)

set.seed(123)
avatar_folds <- vfold_cv(avatar_train, strata =  aang)
avatar_folds

```

```{r}
library(themis)
library(textrecipes)

rec_avatar <- recipe(aang ~ text, data = avatar_train) %>% 
  step_downsample(aang) %>% 
  step_textfeature(text) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())
prep_avatar <- prep(rec_avatar)
juice(prep_avatar)

```

# Build Model

```{r}
rf_spec <- rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

rf_spec

svm_spec <- svm_rbf(cost =  0.5) %>% 
  set_engine("kernlab") %>% 
  set_mode("classification")

svm_spec

wf_avatar <- workflow() %>% 
  add_recipe(rec_avatar)

wf_avatar

```

```{r}
doParallel::registerDoParallel()
set.seed(1234)
rf_rs <- wf_avatar %>% 
  add_model(rf_spec) %>% 
  fit_resamples(
    resamples = avatar_folds,
    metrics = metric_set(roc_auc, accuracy, sens, spec),
    control = control_resamples(save_pred = TRUE)
  )

collect_metrics(rf_rs)
conf_mat_resampled(rf_rs)
```

```{r}
set.seed(2345)
svm_rs <- wf_avatar %>% 
  add_model(svm_spec) %>% 
  fit_resamples(
    resamples = avatar_folds,
    metrics = metric_set(roc_auc, accuracy, sens, spec),
    control = control_resamples(save_pred = TRUE)
  )

collect_metrics(svm_rs)
conf_mat_resampled(svm_rs)
```

# Evaluate model

```{r}
svm_rs %>% 
  collect_predictions() %>% 
  group_by(id) %>% 
  roc_curve(aang, .pred_Aang) %>% 
  ggplot(aes(1 - specificity, sensitivity, color = id))+
  geom_abline(lty = 2, size = 1.5) +
  geom_path(show.legend = FALSE, size  = 1.2) +
  scale_color_avatar("EarthKingdom") +
  coord_equal()
```

```{r}
library(vip)

avatar_imp <- wf_avatar %>% 
  add_model(svm_spec) %>% 
  fit(avatar_train) %>% 
  pull_workflow_fit() %>% 
  vi(method = "permute", nsim = 10,
     target = "aang",
     metric = "auc",
     reference_class = "Other",
     pred_wrapper = kernlab::predict,
     train = juice(prep_avatar))





```

```{r}
avatar_imp %>% 
  mutate(Variable = str_remove(Variable, "textfeature_tesxt_n_"),
         Variable = fct_reorder(Variable, Importance)) %>% 
  slice_max(Importance, n = 8) %>% 
  ggplot(aes(Importance, Variable, color = Variable)) +
  geom_errorbar(aes(xmin = Importance - StDev,
                    xmax = Importance + StDev),
                size = 1) +
  geom_point(size = 3) +
  scale_color_avatar("FireNation")
```

```{r}



```
